### ISSUE TITLE
Add Terminology and rephrase the Token

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-looker-jwt-cwt-status-list#13]
We need a common and better name for the first JWT aka Token aka StatusListEntry.
My proposal would be:
- Subject Token
- **Subject JWT**
- Status Holding JWT

**Comment by tplooker** [comment]
Yes I had a similar thought, I agree with Subject JWT.

**Comment by paulbastian** [comment]
I discussed with @c2bo that the spec is supposed to work for JWT and CWT, so maybe Subject Token might fit better?
